version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "aws-financial-data-pipeline-portfolio"
resolve_s3 = true
s3_prefix = "aws-financial-data-pipeline"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
parameter_overrides = "ProjectName=aws-financial-data-pipeline Environment=portfolio EnableDailySchedule=false"
tags = "Project=aws-financial-data-pipeline Environment=portfolio ManagedBy=AWS-SAM"

[default.delete.parameters]
stack_name = "aws-financial-data-pipeline-portfolio"
region = "us-east-2"
no_prompts = false
